import {sock} from './conexao.js'
//Mapeando comandos
export const ComadosWhats = {
    groupFetchAllParticipating(){},
    CriarGrupo(){},
    getToquen(){return sock.id},
    ObterConviteGrupo(){},
    Metadadosdeumgrupo(){},
    AlterarFotoGrupo(){},
    AddouRemoverPessoas(){},
    EntrandoEmGrupos(){},
    sendMessage(){},
    AddouRemoverPessoas(){},
    AddouRemoverPessoas(){},
    AlterarAsuntoGrupo(){},
    ApenasAdministradores(){},
    ColocarGrupoAberto(){},
    ApenasAdministradorModifiqueOGrupo(){},
    TodosModifiquemOGrupo(){},
    AlterarDescricaoGrupo(){},
    sendMediaAudio(){},
    RevogarConvite(){},
    EnviarLink(){},
    SendBotoes(){},
    AtivarDesativarTempMessage(){},
    sendMessageTemp(){},
    listaBloqueados(){},
    sendMessage(){},
    EncaminhandoMensagem(){},
    sendMessageTemp(){},
    Bloquear(){},
    SendBotoesLINK(){},
    DeletMessage(){},
    sendMediaAudio(){},
    DeletFile(){},
    Upload(){},
    sendImage(){},
    sendFile(){},
    sendPDF(){},
    sendMedia(){},
    enviarLista(){}
} 

